spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
springdoc:
  swagger-ui:
    path: /swagger-ui
