spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER:localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
springdoc:
  swagger-ui:
    path: /swagger-ui
